name: stockhauz
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI/UX
  json_theme: ^5.0.2+6
  salomon_bottom_bar: ^3.3.2

  # State Mgmt
  hooks_riverpod: ^2.3.6
  json_annotation: ^4.8.1
  freezed_annotation: ^2.2.0
  riverpod_annotation: ^2.1.1

  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

  # Routing
  beamer: ^1.5.5

  # Utilities
  path_provider: ^2.0.15
  device_info_plus: ^9.0.2
  package_info_plus: ^4.0.2
  permission_handler: ^10.2.0

  # Local Packages
  font_awesome_flutter:
    path: ./vendor/font_awesome_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  logger: ^1.3.0
  mocktail: ^0.3.0
  build_runner: ^2.4.4
  isar_generator: ^3.1.0+1
  flutter_gen_runner: ^5.3.1

  freezed: ^2.3.4
  custom_lint: ^0.4.0
  riverpod_lint: ^1.3.2
  json_serializable: ^6.7.0
  riverpod_generator: ^2.2.3

  rename: ^2.1.1
  flutter_config: ^2.0.0
  flutter_native_splash: ^2.3.0
  flutter_launcher_icons: ^0.13.1

flutter_gen:
  fonts:
    enabled: true
    outputs:
      class_name: AppFont

  colors:
    enabled: true
    outputs:
        class_name: AppColor
    inputs:
      - assets/themes/app_color.xml

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/themes/

  fonts:
    - family: Cabin
      fonts:
        - asset: assets/fonts/Cabin-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cabin-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Cabin-Bold.ttf
          weight: 700
