name: stockhauz
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI/UX
  json_theme: ^5.0.2+5
  salomon_bottom_bar: ^3.3.2

  # State Mgmt
  equatable: ^2.0.5
  replay_bloc: ^0.2.3
  flutter_bloc: ^8.1.2
  hydrated_bloc: ^9.1.0
  bloc_concurrency: ^0.2.1
  multi_state_bloc: ^0.0.3

  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

  # Routing
  beamer: ^1.5.3

  # Utilities
  path_provider: ^2.0.14
  device_info_plus: ^8.2.2
  package_info_plus: ^3.1.2
  permission_handler: ^10.2.0

  # Local Packages
  font_awesome_flutter:
    path: ./vendor/font_awesome_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  logger: ^1.3.0
  build_runner: ^2.3.3
  isar_generator: ^3.1.0+1
  flutter_gen_runner: ^5.3.0

  rename: ^2.1.1
  flutter_config: ^2.0.0
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.13.1

flutter_gen:
  fonts:
    enabled: true
    outputs:
      class_name: AppFont

  colors:
    enabled: true
    outputs:
        class_name: AppColor
    inputs:
      - assets/themes/app_color.xml

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/themes/

  fonts:
    - family: Cabin
      fonts:
        - asset: assets/fonts/Cabin-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cabin-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Cabin-Bold.ttf
          weight: 700
