name: stockhauz
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI/UX
  json_theme: ^5.0.0+5

  # State Mgmt
  hooks_riverpod: ^2.3.1

  path: ^1.8.2
  drift: ^2.5.0
  path_provider: ^2.0.13
  sqlite3_flutter_libs: ^0.5.13

  # Routing
  beamer: ^1.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  logger: ^1.3.0
  drift_dev: ^2.5.2
  build_runner: ^2.3.3

  rename: ^2.1.1
  flutter_config: ^2.0.0
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.12.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/themes/

  fonts:
    - family: Cabin
      fonts:
        - asset: assets/fonts/Cabin-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cabin-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Cabin-Bold.ttf
          weight: 700
